---
title: "Cross-validators"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Cross-validators}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---



Cross-validators (CV) take a classifier (CL), a datasource (DS) feature preprocessors (FP) objects, and result metric (RM) objects and they run a cross-validation decoding scheme by training and testing the classifier with data generated from the datasource object (and possibly fed through the feature pre-processing first).


## Cross-validators that come with the NDTr

The NDTr comes with one cross-validator:

* `cv_standard`



## Implementing a CV: required methods and data formats

All cross-validators must implement run_decoding() method. This method does not take 
any additional arguments (apart from the cross-validator itself). 

The cross-validator returns a list DECODING_RESULTS which contains different RM
objects that can be used to assess how accurately the classifier made
predictions at different points in time.

Like all NDTr objects, CV objects must also implement a get_properties() method
which returns a data frame with one row that lists all the properties that have
been set to allow for reproducible research.

Like all NDTr objects, CV objects must also implement a get_properties() method
which returns a data frame with one row that lists all the properties that have
been set and also pulls all properties from the other NDTr objects (e.g., from
the DS, FP, CL and RM objects) to allow for reproducible research.



## Example of cross-validators

Examples of using the `cv_standard` can be seen by going through the
introductory tutorial








