---
title: "Isik 26 letter MEG dataset"

output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<div style="line-height: 1.6em;">

The Isik 26 letter MEG dataset was collected by Leyla Isik in Tommy Poggio’s lab and the MEG Lab at the McGovern Institute at MIT. The data was used in Figure 2b of the paper: [The dynamics of invariant object recognition in the human visual system, J.](https://www.physiology.org/doi/full/10.1152/jn.00394.2013) Neurophys 2014.

The data consists of 306 channel (comprised of 102 magentometers, and 204 planar gradiometers) MEG recordings from an Elekta Neuromag Triux Scanner. One subject was shown 26 black, upper-case letters, on a white background, while their neural response was recorded in the MEG scanner. Each letter was presented approximately 50 times. The data is in raster-format, and each trial consists of 233 ms of baseline data where the subject viewed a fixation cross, followed by 50 ms of data when the subject viewed the image of one letter, and 417 ms of data when they again viewed a fixation cross.

The data is available in two formats – the raw MEG files output by the scanner (.fif format) and preprocessed data in [raster format](Raster-format.html). The raw data download also includes a file with raster labels indicating which stimulus was shown in each trial.

decoding procedure multiple times by generating different data splits from the datasource in order to get more robust measures of the decoding accuracy.

</div> 