---
title: "Raster format"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Raster format}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


Raster-format data files contain information from a single site (e.g., data from one neuron, one LFP channel, etc.). Data that is in raster-format contains two variables: raster_data, and raster_site_info, which are described below.


### raster_data

The variables raster_data is a data frame that has variables that must start with two pre-fixes:

1. labels.  These variables contain labels of which experimental conditions were shown on a given trial

2. time.  These variables contain the data for a given time

The number of rows in the data frame correspond to the number of trial in the experiment when the recording was made.


### raster_site_info

Is a list that contains any remaining information that is useful to know about a given site. For example, this could contain information about the brain region a site was recorded from, information about the quality of the recording, etc.



## Example raster-format data

Below is an example of raster format data file from the [Zhang-Desimone 7 object data set](Zhang_Desimone_7_object_dataset.html) .


```{r load_raster_file}

raster_directory_name <- "../data/raster/Zhang_Desimone_7objects_raster_data_rda/"
file_name <- "bp1001spk_01A_raster_data.rda"
load(paste0(raster_directory_name, file_name))

head(raster_data[, 1:10])

head(raster_site_info)


```










