---
title: "Result metrics"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Result metrics}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---



Result metrics (RM) take the predictions made by a classifier and aggregate the
results to that they can be interpreated.

## Result metrics that come with the NDTr

The NDTr comes with 2 result metrics

* `rm_main_results`
* `rm_confusion_matrix`



## Implementing an RM: required methods and data formats

To create a result metric two methods must be implemented
aggregate_CV_split_results() which aggregates the results after a set of
cross-valiation sweeps have been completed and aggregate_resample_run_results()
which aggregates the final results across all the resample runs. 


#### aggregate_CV_split_results() method

The aggregate_CV_split_results() method takes a data frame that is a
contentation of the prediction data frames made by the classifier (CL) objects
across all times and cross-validation splits in one resample run. Thus the input
data frame to the aggregate_CV_split_results() method has similar variables as
in the output of the CL get_predictions() method, namely:

1. CV: a number indicating which cross-validation split the current row comes from                  

2. train_time: the train time that the current row comes from 

3. test_time: the test time that the current row comes from 

4. actual_labels: the labels that were actually present on each trial      

5. predicted_labels: the labels that the classifier predicted

6. decision_vals.X (optional): a group of variables that has values that indicate how strongly
the classifier rates a test point as coming from a particular class


The output of the aggregate_CV_split_results is a RM object of the same type
that contains inherts from a data frame so that the results can be can be
aggregated together (e.g., via rbind) across resample runs. The variables in the
data frame can be anything that is useful to capture about the classification
performance.




#### aggregate_resample_run_results() method

The aggregate_resample_run_results() method takes result metric data frames that
have been aggregated together (e.g., via rbind) across resample runs. Thus this
input data frame as the same variables as the data frame returned by the
aggregate_CV_split_results() along with one additional variable indicating which
resample run each row comes from.

The output of this method should be a RM object of the same type that is a data
frame which most likely is of a smaller size.

Like all NDTr objects, RM objects must also implement a get_properties() method
which returns a data frame with one row that lists all the properties that have
been set to allow for reproducible research.

RM objects can also have plot methods to allow the different aggregated results
to be plotted



## Example of result metrics

Examples of using result metrics can be seen by going through the [Introduction tutorial](introduction_tutorial.html)












