---
title: "Zhang-Desimone 7 object dataset"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Zhang-Desimone 7 object dataset}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---



The Zhang-Desimone 7 object dataset was collected by Ying Zhang in [Bob
Desimone’s lab](http://mcgovern.mit.edu/principal-investigators/robert-desimone)
in the McGovern Institute at MIT. The data was used in the supplemental figures
in the paper [Object decoding with attention in inferior temporal cortex, PNAS,
2011](http://www.pnas.org/content/108/21/8850).

The data consists of single unit recordings from the 132 neurons in inferior
temporal cortex (IT). The recordings were made while a monkey viewed 7 different
objects that were presented at three different locations (the monkey was also
shown images that consisted of three objects shown simultaneously and had to
perform an attention task, however the dataset compiled here only consists of
trials when single objects were shown). Each object was presented approximately
20 times at each of the three locations. The data is in
[raster-format](raster_format.html), and each trial consists of 500 ms of
baseline data where a monkey viewed a fixation dot, and 500 ms of data when a
monkey viewed one of the 7 different images.

